# -*- coding: utf-8 -*-
"""defect detenction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9SC0EErqVdaYlgUXEoGNjkny2LbqUnA
"""

import os
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

torch.__version__

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )


])

TRAIN_DIR = "/content/drive/MyDrive/datasets/NEU-DET/train/images"
VAL_DIR = "/content/drive/MyDrive/datasets/NEU-DET/validation/images"

BATCH_SIZE = 32

train_dataset = datasets.ImageFolder(
    root =TRAIN_DIR,
    transform = train_transform

)


val_dataset = datasets.ImageFolder(
    root = VAL_DIR,
    transform = val_transform
)

train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True)
val_loader = DataLoader(val_dataset, batch_size = 32, shuffle =True)

print(f"classes = {train_dataset.classes}")
print(f"train_dataset = {len(train_dataset)}")
print(f"classes{train_dataset.classes}")

images, labels = next(iter(train_loader))
print(f"images = {len(images)} and {images.shape}")
print(f"labels = {len(labels)} and {labels.shape}")

import torch.nn as nn
import torch.optim as optim
from torchvision import models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

num_classes = len(train_dataset.classes)
model = models.resnet18(pretrained = True)

model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.0001)

num_epochs = 5

for epoch in range(num_epochs):
  model.train()
  running_loss = 0.0
  correct = 0
  total = 0

  for images, labels in train_loader:
    images, labels = images.to(device), labels.to(device)

    optimizer.zero_grad()

    outputs = model(images)
    loss = criterion(outputs, labels)

    loss.backward()
    optimizer.step()


    running_loss += loss.item()
    _,predicted = torch.max(outputs, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()

  train_acc = 100 * correct / total
  print(f"epoch[{epoch+1}/{num_epochs}]"
        f"Loss: {running_loss:.4f}"
        f"Train Accuracy: {train_acc:.2f}%"






)

model.eval()
correct = 0
total = 0


with torch.no_grad():
  for images, labels in val_loader:
    images, labels = images.to(device), labels.to(device)
    outputs = model(images)
    _,predicted = torch.max(outputs, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()

val_acc = 100 * correct/total
print(f"Validation Accuracy: {val_acc:.2f}%")

MODEL_PATH = "/content/drive/MyDrive/defect_model_resnet18.pth"
torch.save(model.state_dict(), MODEL_PATH)